### ISSUE TITLE
make the notebook work w/ Kaggle

### ISSUE THREAD

**Issue by windmaple** [entmike/disco-diffusion-1#6]
The free tier of Colab is too weak. Kaggle offers much better GPU (P100) for free. Would be nice to make it work w/ Kaggle. I'm stuck at install dependencies. 

'pip install -r requirements.txt' gives the following:

```
  WARNING: Did not find branch or tag 'packagify', assuming revision or ref.
  Running command git checkout -q packagify
  error: pathspec 'packagify' did not match any file(s) known to git
  error: subprocess-exited-with-error
  
  × git checkout -q packagify did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -q packagify did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I pip-installed 'packagify' before this too. Didn't work. Any idea?

**Comment by entmike** [comment]
I've never tried using kaggle.  Can you try the `colab-requirements.txt` instead?

**Comment by windmaple** [comment]
`colab-requirements.txt` worked. Hitting another ONNX error, but that's a separate issue. Closing ...
