### ISSUE TITLE
"Fix3d" commit (7d3c396e4e169073862434859b8b3e317193e622) breaks Colab

### ISSUE THREAD

**Issue by davidedc** [entmike/disco-diffusion-1#7]
see error here:
https://stackoverflow.com/questions/72190401/modulenotfounderror-no-module-named-pytorch3d-simplified-disco-diffusion

Cheers a thanks a ton for your work!

**Comment by entmike** [comment]
Thanks for reporting the problem.  The pytorch3dlite stuff was not working for 3d animations so I swapped back to compiled pytorch3d, and forgot to make sure the Colab NBs still worked.  They should be fine now.

**Comment by entmike** [comment]
Issue fixed
